Repository taste-house/mat_zip, pull requests merged in 2024-10, with the labels that each got.

#204 feat: 게시글 상세조회 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/ListDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostCommentDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostDetailResponse.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostDto.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostListResponse.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostTagDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/RestaurantDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/mapper/PostMapper.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/service/PostQueryService.java
  matzipback/src/main/resources/mappers/boardMappers/PostMapper.xml
Labels: feat, chore

#200 fix: #199 리스트 업데이트 기능 로직 수정
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/UpdateListRequset.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyList.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/service/DomainListUpdateService.java
Labels: fix

#174 feat: 활동 등급을 추가하는 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/ActiveLevelController.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/ActiveLevelService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UserActiveLevelRepository.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/ActiveLevelDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/UserActivityDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/ActiveLevelResDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/CreateActiveLevelRequestDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/CreateActiveLevelResMessageDTO.java
Labels: feat

#206 feat: #35 리스트 댓글 수정 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCmtCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/UpdateListCmtRequest.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCmtCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyListComment.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListCmtDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/service/DomainListCmtUpdateService.java
Labels: feat

#205 feat: 리스트 신고 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/service/DomainListService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportListController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportPostController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportListService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportPostService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Report.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/repository/ListDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/service/ListDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/ListReportReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/ListReportReqMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/infrastructure/repository/ListInfraRepository.java
Labels: feat

#211 feat: 음식점 CUD 추가
  matzipback/src/main/java/com/matzip/matzipback/exception/NotFoundException.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/command/application/controller/RestaurantCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/command/application/dto/RestaurantCreateRequest.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/command/application/dto/RestaurantUpdateRequest.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/command/application/service/RestaurantCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/command/domain/aggregate/Restaurant.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/command/domain/repository/RestaurantRepository.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/command/infrastructure/repository/JpaRestaurantRepository.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/command/mapper/RestaurantMapper.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/query/controller/RestaurantQueryController.java
  matzipback/src/main/resources/application.yml
Labels: docs, feat, chore

#215 feat: 스웨거에 커스텀 로그인 필터 활성화
  matzipback/src/main/java/com/matzip/matzipback/config/SwaggerConfig.java
Labels: docs, feat

#178 feat: 회원 등급 테이블 수정 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/repository/PostDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/dto/PostDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportCommandContoller.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Report.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/PostReportResDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/PostReportResReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/ActiveLevelController.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/MessageController.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/ActiveLevelService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/MessageService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Messages.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/MessageRepository.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UserActiveLevelRepository.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/ActiveLevelDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/MessageDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/ActiveLevelResMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/CreateActiveLevelReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/MessageReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/MessageResDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/MessageResMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/UpdateActiveLevelReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/infrastructure/repository/MessageInfraRepository.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/controller/MessageQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/dto/MessageChatResDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/dto/MessageDetailResDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/dto/MessageDetailResMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/dto/SearchMessageListMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/mapper/MessageMapper.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/service/MessageQueryService.java
  matzipback/src/main/resources/application.yml
  matzipback/src/main/resources/mappers/messageMappers/MessageMapper.xml
Labels: feat, chore

#198 feat: 쪽지방 목록 조회 기능
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/ActiveLevelController.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/ActiveLevelService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UserActiveLevelRepository.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/ActiveLevelDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/controller/MessageQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/mapper/MessageMapper.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/service/MessageQueryService.java
  matzipback/src/main/resources/mappers/messageMappers/MessageMapper.xml
Labels: feat

#220 Revert "feat: 쪽지방 목록 조회 기능"
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/ActiveLevelController.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/ActiveLevelService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UserActiveLevelRepository.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/ActiveLevelDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/controller/MessageQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/mapper/MessageMapper.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/service/MessageQueryService.java
  matzipback/src/main/resources/mappers/messageMappers/MessageMapper.xml
Labels: fix

#221 Revert "feat: 회원 등급 테이블 수정 기능 구현"
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/repository/PostDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/dto/PostDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportCommandContoller.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Report.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/PostReportResDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/PostReportResReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/ActiveLevelController.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/MessageController.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/ActiveLevelService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/MessageService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Messages.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/MessageRepository.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UserActiveLevelRepository.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/ActiveLevelDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/MessageDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/ActiveLevelResMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/CreateActiveLevelReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/CreateActiveLevelRequestDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/CreateActiveLevelResMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/MessageReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/MessageResDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/infrastructure/repository/MessageInfraRepository.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/controller/MessageQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/dto/MessageChatResDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/dto/MessageDetailResDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/dto/MessageDetailResMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/dto/SearchMessageListMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/mapper/MessageMapper.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/service/MessageQueryService.java
  matzipback/src/main/resources/application.yml
  matzipback/src/main/resources/mappers/messageMappers/MessageMapper.xml
Labels: fix

#218 feat: 예외 처리 샘플 구조
  matzipback/src/main/java/com/matzip/matzipback/exception/CustomExceptionHandler.java
  matzipback/src/main/java/com/matzip/matzipback/exception/ErrorCode.java
  matzipback/src/main/java/com/matzip/matzipback/exception/ErrorResponse.java
  matzipback/src/main/java/com/matzip/matzipback/exception/RestApiException.java
Labels: feat

#217 feat: 인기 태그 조회 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PopularTagResponse.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/mapper/PostMapper.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/service/PostQueryService.java
  matzipback/src/main/resources/mappers/boardMappers/PostMapper.xml
Labels: feat

#224 refactoring: 유효성관련 글로벌 예외 핸들러 수정
  matzipback/src/main/java/com/matzip/matzipback/exception/GlobalExceptionHandler.java
  matzipback/src/main/java/com/matzip/matzipback/exception/ValidErrorResponse.java
Labels: refactoring

#225 refactoring: 성공 메시지 enum 으로 구현
  matzipback/src/main/java/com/matzip/matzipback/responsemessage/SuccessCode.java
  matzipback/src/main/java/com/matzip/matzipback/responsemessage/SuccessResMessage.java
Labels: refactoring

#229 refactoring: 게시글, 태그 등록 기능 코드 리팩토링
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/PostAndTagRequestDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/TagDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/Post.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/Tag.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/repository/TagRepository.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/infrastructure/repository/TagInfraRepository.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostQueryController.java
Labels: refactoring

#227 refactoring: 게시글 좋아요 코드 리팩토링
  matzipback/src/main/java/com/matzip/matzipback/exception/ErrorCode.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/PostLikeService.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/repository/PostLikeRepository.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/service/PostLikeDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/infrastructure/repository/PostLikeInfraRepository.java
  matzipback/src/main/java/com/matzip/matzipback/like/query/dto/LikedPostDTO.java
  matzipback/src/main/java/com/matzip/matzipback/responsemessage/SuccessCode.java
Labels: refactoring

#235 refactoring: 리스트 댓글 좋아요 기능 리팩토링
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/ListCmtLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/ListCmtLikeReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/ListCmtLikeService.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/ListLikeService.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/repository/ListCmtLikeRepository.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/repository/ListLikeRepository.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/service/ListCmtLikeDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/service/ListLikeDomainService.java
Labels: refactoring

#231 refactor: 댓글 관련 기능 구조에 맞게 리팩토링
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCmtCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ReqPostCmtCreateDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ReqPostCmtDeleteDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ReqPostCmtUpdateDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ResPostCmtDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommentService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostComment.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/repository/PostCommentRepository.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/service/PostCommentDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostCmtLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/PostCmtLikeReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/PostCmtLikeService.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/repository/PostCmtLikeRepository.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/service/PostCmtLikeDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportPostCmtController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportPostCmtService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/repository/ReportDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/service/ReportDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/PostCmtReportReqDTO.java
Labels: fix, refactoring, feat, chore

#249 refactor: 게시글 신고 기능 리팩토링
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportPostCmtController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportPostController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportPostCmtService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportPostService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Report.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/service/ReportDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/PostCmtReportResMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/PtAndCmtReportReqDTO.java
Labels: fix, refactoring, feat, chore, style

#244 feat: 리뷰 작성 기능 추가
  matzipback/build.gradle
  matzipback/src/main/java/com/matzip/matzipback/common/util/FileUploadUtils.java
  matzipback/src/main/java/com/matzip/matzipback/config/MultipartJackson2HttpMessageConverter.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/command/application/service/RestaurantCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/command/domain/aggregate/Restaurant.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/application/controller/ReviewCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/application/dto/ReviewCreateRequest.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/application/dto/ReviewImageRequest.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/application/service/ReivewCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/domain/aggregate/Review.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/domain/aggregate/ReviewImage.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/domain/repository/ReviewImageRepository.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/domain/repository/ReviewRepository.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/infrastructure/repository/JpaReviewImageRepository.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/infrastructure/repository/JpaReviewRepository.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/mapper/ReviewMapper.java
  matzipback/src/main/java/com/matzip/matzipback/review/query/controller/ReviewQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/review/query/mapper/ReviewMapper.java
  matzipback/src/main/java/com/matzip/matzipback/review/query/service/ReviewQueryService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/UserActivityDomainService.java
  matzipback/src/main/resources/application.yml
  matzipback/src/main/resources/mappers/ReviewMappers/ReviewMapper.xml
Labels: feat

#239 feat: #40 맛집 가져오기 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/exception/ErrorCode.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/MatzipCollectCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/MatzipCollectReq.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/MatzipCollectService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyListMatzip.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/MatzipCollectDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/MatzipDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/infrastructure/repository/InfraMatzipCollectRepository.java
Labels: feat

#246 feat: 인기 태그 제시 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/mapper/PostMapper.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/service/PostQueryService.java
  matzipback/src/main/resources/mappers/boardMappers/PostMapper.xml
Labels: feat, chore

#222 feat: #36 리스트 댓글 신고 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/service/DomainListCmtService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportListController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportListService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Report.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/repository/ListDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/service/ListDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/ListCmtReportReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/ListCmtReportReqMessageDTO.java
Labels: feat

#192 feat: #74 회원정보 전체 조회 및 정렬 구현
  matzipback/src/main/java/com/matzip/matzipback/report/query/dto/PenaltyDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/controller/UsersQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/dto/userInfo/AllUserInfoResponseDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/dto/userInfo/BusinessLicenseDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/dto/userInfo/UserActivityInfoDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/dto/userInfo/UserInfoDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/mapper/UsersInfoMapper.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/service/UsersInfoService.java
  matzipback/src/main/resources/mappers/usersMappers/UserListMapper.xml
Labels: feat, chore, rename

#254 docs: README 추가
  README.md
  assets/images/erd/conceptual_model.png
  assets/images/erd/logical_model.png
  assets/images/erd/physical_model.png
Labels: docs

#257 feat: 게시글 등록, 삭제 시 회원 활동포인트 업데이트
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/PostAndTagRequestDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommandService.java
Labels: refactoring, feat

#255 feat: #21 리스트 서랍 수정 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListBoxCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/ListBoxUpdateRequest.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListBoxCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyList.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListDomainRepository.java
Labels: feat

#259 chore: #258 리스트 댓글 등록/삭제 시 점수 획득/차감 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/DeleteListCmtRequset.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCmtCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListCmtDomainRepository.java
Labels: chore

#267 feat: 리뷰 수정, 삭제 기능 추가
  matzipback/src/main/java/com/matzip/matzipback/exception/ErrorCode.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/application/controller/ReviewCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/application/dto/ReviewUpdateRequest.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/application/service/ReviewCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/domain/aggregate/Review.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/domain/repository/ReviewRepository.java
  matzipback/src/main/resources/mappers/ReviewMappers/ReviewMapper.xml
Labels: feat

#266 test: 게시글 등록, 수정, 삭제, 조회 테스트 코드 작성
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/PostAndTagRequestDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/Post.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PopularTagResponse.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostCommentDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostDetailResponse.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostListResponse.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostTagDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/RestaurantDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/service/PostQueryService.java
  matzipback/src/test/java/com/matzip/matzipback/board/command/application/service/PostCommandServiceTest.java
  matzipback/src/test/java/com/matzip/matzipback/board/query/service/BoardQueryServiceTest.java
  matzipback/src/test/java/com/matzip/matzipback/board/query/service/PostQueryServiceTest.java
Labels: test, chore

#263 회원 조회 테스트
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/EmailController.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/UsersCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/EmailSendRequest.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/controller/UsersQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/dto/userInfo/OtherUserInfoDto.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/dto/userInfo/UserDetailInfoDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/mapper/UsersInfoMapper.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/mapper/UsersMapper.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/service/UsersInfoService.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/service/UsersQueryService.java
  matzipback/src/main/resources/mappers/usersMappers/UserListMapper.xml
  matzipback/src/test/java/com/matzip/matzipback/users/query/service/UsersInfoServiceTest.java
Labels: refactoring, test

#264 refactoring: 회원관리, 이메일쪽 1차 리팩토링
  matzipback/src/main/java/com/matzip/matzipback/responsemessage/SuccessCode.java
  matzipback/src/main/java/com/matzip/matzipback/responsemessage/SuccessSearchResMessage.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/EmailController.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/UsersCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/controller/UsersQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/service/UsersInfoService.java
Labels: refactoring, chore

#270 chore: 리스트 스웨거 어노테이션 수정
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListBoxCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/MatzipCollectCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/MatzipCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/ListQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/MatzipQueryController.java
Labels: chore

#268 docs: README 프로젝트 개요 작성, DDL 추가, ERD 수정
  README.md
  assets/images/ddl/matzip_ddl.sql
  assets/images/erd/conceptual_model.png
Labels: docs

#271 feat: 음식점 별 리뷰 조회 추가
  matzipback/src/main/java/com/matzip/matzipback/review/query/controller/ReviewQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/review/query/dto/ReviewByRestaurantDTO.java
  matzipback/src/main/java/com/matzip/matzipback/review/query/dto/ReviewByRestaurantResponse.java
  matzipback/src/main/java/com/matzip/matzipback/review/query/mapper/ReviewMapper.java
  matzipback/src/main/java/com/matzip/matzipback/review/query/service/ReviewQueryService.java
  matzipback/src/main/resources/mappers/ReviewMappers/ReviewMapper.xml
Labels: feat

#272 feat: yaml파일 수정(비밀키 분리, 스웨거 탭 닫은 상태로 시작)
  matzipback/src/main/resources/application.yml
Labels: docs, chore

#277 feat: 신고 검색 및 조회, 상세조회 기능 추가
  matzipback/src/main/java/com/matzip/matzipback/report/query/controller/ReportQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/dto/ReasonDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/dto/ReportDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/dto/ReportDetailResponse.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/dto/ReportListResponse.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/mapper/ReportMapper.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/service/ReportQueryService.java
  matzipback/src/main/resources/mappers/reportMappers/ReportMapper.xml
Labels: feat

#274 chore: #273 userSeq 수정
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListBoxCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCommandService.java
Labels: chore

#276 test: #275 리스트 등록, 수정, 삭제 테스트 코드 구현
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/DeleteListRequest.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/UpdateListRequest.java
  matzipback/src/test/java/com/matzip/matzipback/matzipList/command/application/service/ListCommandServiceTest.java
Labels: test

#279 test: #278 리스트 댓글 등록, 수정, 삭제 테스트 코드 구현
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/DeleteListCmtRequset.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyListComment.java
  matzipback/src/test/java/com/matzip/matzipback/matzipList/command/application/service/ListCmtCommandServiceTest.java
Labels: test

#283 test: #282 리스트 맛집 등록, 수정, 삭제 테스트 코드 구현
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/DeleteMatzipRequest.java
  matzipback/src/test/java/com/matzip/matzipback/matzipList/command/application/service/MatzipCommandServiceTest.java
Labels: test

#281 test: 댓글 CUD 기능에 대한 테스트 코드 작성 및 테스트 확인
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ReqPostCmtUpdateDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/service/PostCommentDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/infrastructure/repository/PostCommentInfraRepository.java
  matzipback/src/test/java/com/matzip/matzipback/board/command/application/service/PostCommentServiceTest.java
Labels: feat, test, chore

#287 test: 회원 본인이 작성한 댓글 조회 기능 테스트
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/PostCmtLikeService.java
  matzipback/src/test/java/com/matzip/matzipback/board/query/service/PostCmtQueryServiceTest.java
Labels: test

#289 feat: 패널티 등록, 수정, 철회 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/Post.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostComment.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyList.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyListComment.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/PenaltyCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/PenaltyCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Penalty.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Report.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/ReportView.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/repository/PenaltyRepository.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/repository/ReportDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/repository/ReportViewRepository.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/PenaltyUpdateRequest.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/ReportAndPenaltyDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/infrastructure/repository/PenaltyInfraRepository.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/infrastructure/repository/ReportViewInfraRepository.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/domain/aggregate/Review.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Users.java
  matzipback/src/test/java/com/matzip/matzipback/report/command/application/service/PenaltyCommandServiceTest.java
Labels: feat, test

#285 test: 게시물 댓글 좋아요/좋아요 취소 테스트 코드 작성 및 확인
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostCmtLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/PostCmtLikeReqDTO.java
  matzipback/src/test/java/com/matzip/matzipback/like/command/application/service/PostCmtLikeServiceTest.java
Labels: test, chore

#288 test: 이메일관련, 회원관련 서비스 테스트 완료
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/EmailService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/UsersCommandService.java
  matzipback/src/test/java/com/matzip/matzipback/users/command/application/service/EmailServiceTest.java
  matzipback/src/test/java/com/matzip/matzipback/users/command/application/service/UsersCommandServiceTest.java
  matzipback/src/test/java/com/matzip/matzipback/users/query/service/UsersInfoServiceTest.java
Labels: fix, test, chore

#291 chore: 게시글 댓글 기능 스웨거 테스트를 위한 설정
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCmtCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostCmtLikeController.java
Labels: chore

#293 chore: 스웨거 설정을 위한 어노테이션 추가 및 안쓰는코드 삭제
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/UsersAuthController.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/UsersInfoController.java
Labels: refactoring, chore

#295 chore: 게시물 댓글 조회 DTO 및 쿼리문 수정
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostCommentDTO.java
  matzipback/src/main/resources/mappers/boardMappers/PostCmtMapper.xml
Labels: chore

#298 docs: Readme 게시글 댓글 테스트 결과 입력
  README.md
  assets/images/test/postcomment/postCmtCreate.png
  assets/images/test/postcomment/postCmtDelete.jpeg
  assets/images/test/postcomment/postCmtLike.jpeg
  assets/images/test/postcomment/postCmtNotLike.jpeg
  assets/images/test/postcomment/postCmtRead.jpeg
  assets/images/test/postcomment/postCmtUpdate.jpeg
Labels: docs

#299 chore: 리스트 댓글 어노테이션 수정
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCmtCommandController.java
Labels: chore

#301 docs: readme 게시물 댓글 조회 테스트 추가
  README.md
Labels: docs

#305 feat: 게시판 즐겨찾기 등록, 취소 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/BoardCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/BoardLikeDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/BoardCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/repository/BoardDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/service/BoardDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/infrastructure/repository/BoardInfraRepository.java
Labels: feat

#309 fix: 관리자 검색용 쿼리 수정(테스트를 위해 바꾼 코드가 문제가 됨)
  matzipback/src/main/resources/mappers/usersMappers/UserListMapper.xml
Labels: fix

#310 refactoring: 유저 인가 기능 추가
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/BoardCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCmtCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/BoardCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommentService.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/BoardQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostCmtQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/exception/CustomExceptionHandler.java
  matzipback/src/main/java/com/matzip/matzipback/exception/GlobalExceptionHandler.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/ListCmtLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/ListLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostCmtLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/PostLikeService.java
  matzipback/src/main/java/com/matzip/matzipback/like/query/controller/LikeController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListBoxCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCmtCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportPostCmtService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportPostService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/repository/ReportDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/service/ReportDomainService.java
Labels: refactoring, feat

#311 docs: 테스트 사진 추가
  assets/images/test/board/Screenshot 2024-10-04 at 05.39.43.JPG
  assets/images/test/board/게시글_좋아요.JPG
  assets/images/test/board/게시판_즐겨찾기_전체_조회.JPG
  assets/images/test/board/즐겨찾기한_게시판_조회.JPG
  assets/images/test/board/즐겨찾기한_게시판_취소.JPG
  assets/images/test/like/좋아요한_게시글_조회.JPG
  assets/images/test/report/게시글_신고.JPG
Labels: docs

#315 docs: DDD, SRS, 회고 등 추가
  README.md
  assets/images/ddd/EventStorming.jpg
  assets/images/srs/srs.png
Labels: docs

#321 docs: readme 수정
  README.md
  assets/images/API/API.png
  assets/images/MSA/MSA.jpg
  assets/images/ddl/matzip_ddl.sql
  assets/images/srs/srs.png
Labels: docs

#322 docs: Update README.md
  README.md
Labels: docs

#324 docs: readme 수정
  README.md
  assets/api-docs/Swagger UI.mhtml
Labels: docs

#334 feat: 쪽지 보내기 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/config/SwaggerConfig.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/LikeCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/application/controller/MessageController.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/application/dto/SendMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/application/service/MessageService.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/domain/aggregate/Messages.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/domain/repository/MessageDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/domain/service/MessageDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/infrastructure/repository/MessageInfraRepository.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/HMACKeyGenerator.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/config/SecurityConfig.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/dto/LoginRequestDTO.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/filter/CustomAuthenticationFilter.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/handler/LoginFailureHandler.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/handler/LoginSuccessHandler.java
Labels: fix, feat

#336 feat: 쪽지방 목록 조회 구현
  matzipback/src/main/java/com/matzip/matzipback/message/query/controller/MessageQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/message/query/dto/MessageShortDTO.java
  matzipback/src/main/java/com/matzip/matzipback/message/query/mapper/MessageMapper.java
  matzipback/src/main/java/com/matzip/matzipback/message/query/service/MessageQueryService.java
  matzipback/src/main/resources/mappers/MessageMappers/MessageMapper.xml
Labels: feat

#339 feat: 쪽지방 상세 조회 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCmtCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/BoardQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostCmtQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/ListCmtLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/ListLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostCmtLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/ReviewLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/ReviewLikeDTO.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/ReviewLikeService.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/repository/ReviewLikeRepository.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/service/ReviewLikeDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/infrastructure/repository/ReviewLikeInfraRepository.java
  matzipback/src/main/java/com/matzip/matzipback/like/query/controller/LikeController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListBoxCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCmtCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/MatzipCollectCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/MatzipCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/ListQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/MatzipQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/message/query/controller/MessageQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/message/query/dto/MessageDetailDTO.java
  matzipback/src/main/java/com/matzip/matzipback/message/query/mapper/MessageMapper.java
  matzipback/src/main/java/com/matzip/matzipback/message/query/service/MessageQueryService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/PenaltyCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportListController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportPostCmtController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportPostController.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/controller/ReportQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/command/application/controller/RestaurantCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/query/controller/RestaurantQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/application/controller/ReviewCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/review/query/controller/ReviewQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/config/SecurityConfig.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/util/UserFeignClient.java
  matzipback/src/main/resources/mappers/MessageMappers/MessageMapper.xml
  matzipuser/src/main/java/com/matzip/matzipuser/users/command/application/controller/UsersAuthController.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/query/controller/ActiveLevelQueryController.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/query/controller/UsersActivityQueryController.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/query/controller/UsersFollowQueryController.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/query/controller/UsersQueryController.java
Labels: feat

#342 feat: 쪽지 삭제 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/message/command/application/controller/MessageController.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/application/service/MessageService.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/domain/aggregate/Messages.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/domain/repository/MessageDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/domain/service/MessageDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/message/query/dto/MessageDetailDTO.java
  matzipback/src/main/resources/mappers/MessageMappers/MessageMapper.xml
Labels: refactoring, feat

#345 feat: 회원 활동 등급 수정, 삭제 기능 (관리자 기능)
  matzipuser/src/main/java/com/matzip/matzipuser/exception/ErrorCode.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/command/application/controller/ActiveLevelController.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/command/application/dto/UpdateActiveLevelDTO.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/command/application/service/ActiveLevelService.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/command/domain/repository/UserActiveLevelRepository.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/command/domain/service/ActiveLevelDomainService.java
Labels: refactoring, feat

#346 feat: 쪽지 신고 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/exception/ErrorCode.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportMessageController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/PenaltyCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportMessageService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/repository/ReportRepository.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/service/DomainReportMessageService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/service/ReportDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/SaveMessageReportDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/infrastructure/repository/ReportInfraRepository.java
  matzipback/src/main/java/com/matzip/matzipback/responsemessage/SuccessCode.java
Labels: feat, chore
