Repository taste-house/mat_zip, pull requests merged in 2024-09, with the labels that each got.

#6 Chore 기존 테스트 코드 제거, CQRS 구조 수정
  matzipback/src/main/java/com/matzip/matzipback/test/command/application/controller/ApplicationTestController.java
  matzipback/src/main/java/com/matzip/matzipback/test/command/application/service/ApplicationTestService.java
  matzipback/src/main/java/com/matzip/matzipback/test/command/controllers/TestController.java
  matzipback/src/main/java/com/matzip/matzipback/test/command/domain/repository/DomainTestRepository.java
  matzipback/src/main/java/com/matzip/matzipback/test/command/domain/service/DomainTestService.java
  matzipback/src/main/java/com/matzip/matzipback/test/command/entities/Test.java
  matzipback/src/main/java/com/matzip/matzipback/test/command/infrastructure/repository/InfraTestRepository.java
  matzipback/src/main/java/com/matzip/matzipback/test/command/infrastructure/service/InfraTestService.java
  matzipback/src/main/java/com/matzip/matzipback/test/command/repositories/TestRepository.java
  matzipback/src/main/java/com/matzip/matzipback/test/command/services/TestDTO.java
  matzipback/src/main/java/com/matzip/matzipback/test/command/services/TestService.java
  matzipback/src/main/java/com/matzip/matzipback/test/query/controller/TestQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/test/query/controllers/TestQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/test/query/mapper/TestQueryMapper.java
  matzipback/src/main/java/com/matzip/matzipback/test/query/mappers/TestMapper.java
  matzipback/src/main/java/com/matzip/matzipback/test/query/service/TestQueryService.java
  matzipback/src/main/java/com/matzip/matzipback/test/query/services/TestQueryDTO.java
  matzipback/src/main/java/com/matzip/matzipback/test/query/services/TestQueryService.java
Labels: chore

#49 feat: 게시판 Entity 생성
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/BoardCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/BoardCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/BoardCategory.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/FavoriteBoard.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/Post.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostComment.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostImage.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostTag.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/Tag.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/repository/BoardDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/service/BoardDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/infrastructure/repository/BoardInfraRepository.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/infrastructure/service/BoardInfraService.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/BoardQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/mapper/BoardMapper.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/service/BoardQueryService.java
Labels: feat

#51 chore: ddl-auto, mapper-locations 수정
  matzipback/src/main/resources/application.yml
Labels: chore

#56 feat:맛집 List 파일 추가
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ApplicationListController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ApplicationListService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/DomainListRepository.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/service/DomainListService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/infrastructure/repository/InfraListRepository.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/infrastructure/service/InfraListService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/ListQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/mapper/ListQueryMapper.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/service/ListQueryService.java
Labels: feat

#57 feat: list/domain/command/aggregate 파일 추가
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyList.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyListComment.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyListMatzip.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/Restaurant.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/Review.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/ReviewImage.java
Labels: feat

#58 feat: 게시판 카테고리 전체 조회 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/BoardQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/BoardCategoryDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/mapper/BoardMapper.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/service/BoardQueryService.java
  matzipback/src/main/resources/mappers/boardMappers/BoardMapper.xml
Labels: feat

#61 test: 게시판 전체 목록 조회 Test code 구현
  matzipback/src/test/java/com/matzip/matzipback/board/query/service/BoardQueryServiceTest.java
Labels: test

#63 feat: 게시판 즐겨찾기 목록 조회 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/BoardQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/mapper/BoardMapper.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/service/BoardQueryService.java
  matzipback/src/main/resources/mappers/boardMappers/BoardMapper.xml
Labels: feat

#93 회원관리 및 신고쪽 Entity 및 파일 생성
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportCommandContoller.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Penalty.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Reason.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Report.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/ReportReason.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/repository/ReportDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/service/ReportDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/infrastructure/repository/ReportInfraRepository.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/infrastructure/service/ReportInfraService.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/controller/ReportQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/mapper/ReportMapper.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/service/ReportQueryService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/UsersCommandContoller.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/UsersCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/BusinessLicense.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Messages.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/UserStatus.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Users.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UsersDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/UsersDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/infrastructure/repository/UsersInfraRepository.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/infrastructure/service/UsersInfraService.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/controller/UsersQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/mapper/UsersMapper.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/service/UsersQueryService.java
Labels: feat

#95 chore: 시퀀스 타입 변경 int -> long
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyList.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyListComment.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyListMatzip.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/Restaurant.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/Review.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/ReviewImage.java
Labels: chore

#96 chore: 회원관리, 신고 엔티티 시퀀스 데이터 타입 변경
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Penalty.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Reason.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Report.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/ReportReason.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/BusinessLicense.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Messages.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Users.java
Labels: chore

#98 feat: 게시글 댓글 작성 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommentController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/RequestPostCommentDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ResponsePostCommentDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommentService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostComment.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/repository/PostCommentRepository.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/service/PostCommentDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/infrastructure/repository/PostCommentInfraRepository.java
Labels: feat, chore

#100 fix: 게시글 댓글 작성 기능 버그 수정
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommentController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommentService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/repository/PostCommentRepository.java
Labels: fix, chore

#104 feat : 회원가입, 로그인 구현
  matzipback/build.gradle
  matzipback/src/main/java/com/matzip/matzipback/config/AppConfig.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/HMACKeyGenerator.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/config/SecurityConfig.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/dto/ExceptionResponseDTO.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/dto/LoginRequestDTO.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/filter/CustomAuthenticationFilter.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/filter/JwtFilter.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/handler/JwtAccessDeniedHandler.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/handler/JwtAuthenticationEntryPoint.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/handler/LoginFailureHandler.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/handler/LoginSuccessHandler.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/util/CustomUserDetailService.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/util/JwtUtil.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/UsersCommandContoller.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/UsersCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Users.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UsersDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/CreateUserRequest.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/infrastructure/repository/UsersInfraRepository.java
  matzipback/src/main/resources/application.yml
Labels: feat, chore

#105 feat: 게시물 댓글 수정 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommentController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ReqPostCmtCreateDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ReqPostCmtUpdateDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ResPostCmtDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommentService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostComment.java
Labels: feat, chore

#106 회원, 신고 엔티티 생성 및 데이터타입 변경
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Penalty.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Reason.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Report.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/ReportReason.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/ActiveLevel.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/BusinessLicense.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Follow.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/MessageBlock.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Messages.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/UserActivity.java
Labels: feat, chore

#108 feat: 게시물 댓글 삭제 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommentController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ReqPostCmtDeleteDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommentService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostComment.java
Labels: feat, chore

#111 feat: 게시글 검색 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/Post.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostComment.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostImage.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostTag.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/Tag.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostDto.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostListResponse.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/mapper/PostMapper.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/service/PostQueryService.java
  matzipback/src/main/resources/mappers/boardMappers/PostMapper.xml
Labels: feat, chore

#113 chore: 댓글 관련 기능 수정
  matzipback/src/main/java/com/matzip/matzipback/MatzipbackApplication.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommentController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommentService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostComment.java
  matzipback/src/main/java/com/matzip/matzipback/config/ModelMapperConfig.java
  matzipback/src/main/resources/application.yml
Labels: fix, feat, chore

#116 feat: userDeatils에서 사용자 정보 가져오는 공통 기능 추가
  matzipback/src/main/java/com/matzip/matzipback/common/util/CustomUserUtils.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/config/SecurityConfig.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/util/CustomUserDetailService.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/util/JwtUtil.java
Labels: feat

#119 feat: #23 리스트 생성 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ApplicationListController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/CreateListRequest.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ApplicationListService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyList.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/DomainListRepository.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/infrastructure/repository/InfraListRepository.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/mapper/ListMapper.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListCategoryDTO.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListSearchAllDTO.java
  matzipback/src/main/resources/mappers/listMappers/ListQueryMapper.xml
  matzipback/src/test/java/com/matzip/matzipback/matzipList/command/application/controller/ListCommandControllerTest.java
Labels: feat

#121 Feat: 게시물 댓글 좋아요/좋아요 취소 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/LikeCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostCmtLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/LikeCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/PostCmtLikeService.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/aggregate/Like.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/repository/LikeDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/repository/PostCmtLikeRepository.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/service/LikeDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/infrastructure/repository/PostCmtLikeInfraRepository.java
  matzipback/src/main/java/com/matzip/matzipback/like/query/mapper/LikeQueryMapper.java
  matzipback/src/main/java/com/matzip/matzipback/like/query/service/LikeQueryService.java
  matzipback/src/main/resources/mappers/likeMappers/LikeQueryMapper.xml
Labels: feat

#123 chore: 게시글 댓글 삭제 기능 요청 방법 수정 및 응답 반환형 수정
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommentController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommentService.java
Labels: chore

#122 feat: 게시글 삭제 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/Post.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/repository/PostRepository.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/infrastructure/repository/PostInfraRepository.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostQueryController.java
Labels: feat, chore

#124 Feat/list/list search
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/ListQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListSearchAllDTO.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/mapper/ListQueryMapper.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/service/ListQueryService.java
  matzipback/src/main/resources/mappers/listMappers/ListQueryMapper.xml
Labels: feat

#126 feat: 게시글 신고 기능 추가
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/service/PostDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportCommandContoller.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Report.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/repository/ReportDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/service/ReportDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/PostReportReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/PostReportResMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/infrastructure/repository/ReportInfraRepository.java
  matzipback/src/main/java/com/matzip/matzipback/responsemessage/ResponseMessage.java
Labels: feat, chore

#128 fix: #23 리스트 생성 테스트 코드로 변경
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/mapper/ListQueryMapper.java
Labels: fix

#129 fix: #23 리스트 등록 시 level 자동 생성 로직 변경
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/ListQueryController.java
Labels: fix, chore

#131 feat: #127 다른 유저의 리스트 서랍 조회 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/ListQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListSearchUserDTO.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/mapper/ListQueryMapper.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/service/ListQueryService.java
  matzipback/src/main/resources/mappers/listMappers/ListQueryMapper.xml
Labels: feat

#133 feat: 회원 본인이 작성한 댓글들 조회하는 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostCmtQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostCmtListResponseDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostCommentDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/mapper/PostCmtMapper.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/service/PostCmtQueryService.java
  matzipback/src/main/resources/mappers/boardMappers/PostCmtMapper.xml
Labels: feat, chore

#136 chore: 회원 본인이 작성한 게시글 댓글 조회 서비스 로직, 쿼리문 수정
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostCommentDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/service/PostCmtQueryService.java
  matzipback/src/main/resources/mappers/boardMappers/PostCmtMapper.xml
Labels: chore

#138 feat: #24 리스트 삭제 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListDomainRepository.java
Labels: feat

#137 feat: 게시글 좋아요 기능 추가
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/PostLikeReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/PostLikeResMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/PostLikeService.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/aggregate/Like.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/repository/PostLikeRepository.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/service/PostLikeDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/infrastructure/repository/PostLikeInfraRepository.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/UsersCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/UserActivity.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UserActivityRepository.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/UserActivityDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/infrastructure/repository/UserActivityInfraRepository.java
Labels: feat

#139 feat: #22 리스트 상세조회 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/ListQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListCategoryDTO.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListContentDTO.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/MatzipDTO.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/mapper/ListQueryMapper.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/service/ListQueryService.java
  matzipback/src/main/resources/mappers/listMappers/ListQueryMapper.xml
Labels: feat

#142 feat: 좋아요 게시글 조회 기능 추가
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostCommentDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/service/PostCmtQueryService.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/PostLikeReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/PostLikeService.java
  matzipback/src/main/java/com/matzip/matzipback/like/query/controller/LikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/query/dto/LikedPostDTO.java
  matzipback/src/main/java/com/matzip/matzipback/like/query/dto/LikedPostResMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/like/query/mapper/LikeQueryMapper.java
  matzipback/src/main/java/com/matzip/matzipback/like/query/service/LikeQueryService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/ListQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/mapper/ListQueryMapper.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/service/ListQueryService.java
  matzipback/src/main/resources/mappers/likeMappers/LikeQueryMapper.xml
  matzipback/src/main/resources/mappers/listMappers/ListQueryMapper.xml
Labels: refactoring, feat

#151 chore: 충돌 해결하면서 지워진 메서드 추가
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListDomainRepository.java
Labels: chore

#134 회원가입 기능 추가
  matzipback/build.gradle
  matzipback/src/main/java/com/matzip/matzipback/exception/GlobalExceptionHandler.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/EmailController.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/UsersCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/EmailService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/UsersCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/utility/UUIDGenerator.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Users.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UsersDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/CreateSocialRequest.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/CreateUserRequest.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/EmailChkRequest.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/EmailRequest.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/controller/UsersQueryController.java
  matzipback/src/main/resources/application.yml
Labels: refactoring, feat, chore

#149 feat: #29 리스트 내 맛집 검색 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/MatzipQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/MatzipSearchDTO.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/mapper/MatzipQueryMapper.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/service/MatzipQueryService.java
  matzipback/src/main/resources/mappers/listMappers/MatzipQueryMapper.xml
Labels: feat

#153 feat: 팔로우 등록, 취소 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/responsemessage/ResponseMessage.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/UsersFollowController.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/UsersFollowService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Follow.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/FollowId.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UsersFollowRepository.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/UsersFollowDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/FollowDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/FollowResMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/infrastructure/repository/UsersFollowInfraRepository.java
Labels: feat

#157 feat: 음식점 검색, 음식점 상세조회 기능 추가
  matzipback/src/main/java/com/matzip/matzipback/restaurant/command/aggregate/Restaurant.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/query/controller/RestaurantQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/query/dto/RestaurantDetailResponse.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/query/dto/RestaurantDto.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/query/dto/RestaurantListResponse.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/query/mapper/RestaurantMapper.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/query/service/RestaurantQueryService.java
  matzipback/src/main/resources/mappers/restaurantMappers/RestaurantMapper.xml
Labels: feat

#148 fix: 댓글 수정 로직 수정
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ReqPostCmtCreateDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommentService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostComment.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostCmtLikeController.java
Labels: fix

#158 feat: 팔로잉 목록 조회
  matzipback/src/main/java/com/matzip/matzipback/users/query/controller/UsersFollowQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/dto/FollowQueryResMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/dto/FollowingUsersDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/mapper/UsersFollowMapper.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/service/UsersFollowQueryService.java
  matzipback/src/main/resources/mappers/followMappers/UsersFollowMappers.xml
Labels: feat

#159 feat: 팔로워 목록 조회 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/users/query/controller/UsersActivityQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/controller/UsersFollowQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/dto/UsersActivityDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/dto/UsersActivityQueryResMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/mapper/UsersActivityMapper.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/mapper/UsersFollowMapper.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/service/UsersActivityQueryService.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/service/UsersFollowQueryService.java
  matzipback/src/main/resources/mappers/UserActvitiyMappers/UsersActivityMapper.xml
  matzipback/src/main/resources/mappers/followMappers/UsersFollowMappers.xml
Labels: feat

#161 feat: #33 리스트 댓글 작성 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCmtCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/CreateListCmtRequest.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCmtCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyListComment.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListCmtDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/infrastructure/repository/InfraListCmtDomainRespository.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/mapper/ListCmtMapper.java
Labels: feat

#173 feat: #37 리스트 좋아요 등록 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/ListLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/ListLikeMessageReqDto.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/ListLikeReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/ListLikeService.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/repository/ListLikeRepository.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/service/ListLikeDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/infrastructure/repository/ListLikeInfraRepository.java
Labels: feat

#168 feat: #27 리스트 내 맛집 등록 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/MatzipCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/CreateMatzipRequest.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/MatzipCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyListMatzip.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/MatzipDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/infrastructure/repository/InfraMatzipRepository.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/mapper/MatzipMapper.java
Labels: feat

#176 feat: 게시글 작성, 태그 등록 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/CreatePostAndTagReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/Post.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostTag.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/repository/PostRepository.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/repository/PostTagRepository.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/infrastructure/repository/PostTagInfraRepository.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostQueryController.java
Labels: feat, chore

#177 feat: #79, #80 회원정보 수정, 탈퇴
  matzipback/src/main/java/com/matzip/matzipback/exception/GlobalExceptionHandler.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/UsersCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/UsersCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Users.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UsersDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/DeleteUserRequest.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/dto/UpdateUserRequest.java
Labels: feat, chore

#166 refactoring: 다른 유저도 팔로잉 목록을 조회할 수 있도록 수정
  matzipback/src/main/java/com/matzip/matzipback/users/query/controller/UsersFollowQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/mapper/UsersFollowMapper.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/service/UsersFollowQueryService.java
Labels: refactoring

#169 feat: 회원 등급 자동 변경 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/ActiveLevel.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/UserActivity.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UserActiveLevelRepository.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/UserActiveLevelDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/UserActivityDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/infrastructure/repository/UsersActiveLevelInfraRepository.java
Labels: feat

#180 Feat: #25 리스트 업데이트 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/UpdateListRequset.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyList.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/service/DomainListUpdateService.java
Labels: feat

#179 feat: 리뷰 검색 및 조회 기능 추가
  matzipback/src/main/java/com/matzip/matzipback/review/query/controller/ReviewQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/review/query/dto/ReviewDetailResponse.java
  matzipback/src/main/java/com/matzip/matzipback/review/query/dto/ReviewImageDto.java
  matzipback/src/main/java/com/matzip/matzipback/review/query/dto/ReviewImageResponse.java
  matzipback/src/main/java/com/matzip/matzipback/review/query/dto/ReviewListDto.java
  matzipback/src/main/java/com/matzip/matzipback/review/query/dto/ReviewListResponse.java
  matzipback/src/main/java/com/matzip/matzipback/review/query/mapper/ReviewMapper.java
  matzipback/src/main/java/com/matzip/matzipback/review/query/service/ReviewQueryService.java
  matzipback/src/main/resources/mappers/ReviewMappers/ReviewMapper.xml
Labels: feat

#171 feat: 활동 등급 전체 조회 구현
  matzipback/src/main/java/com/matzip/matzipback/users/query/controller/ActiveLevelQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/dto/ActiveLevelDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/dto/ActiveLevelResMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/mapper/ActiveLevelMapper.java
  matzipback/src/main/java/com/matzip/matzipback/users/query/service/ActiveLevelQueryService.java
  matzipback/src/main/resources/mappers/ActiveLevelMappers/ActiveLevelMapper.xml
Labels: feat

#194 refactor: 댓글 관련 기능 리팩토링
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCmtCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommentController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ReqPostCmtUpdateDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ResPostCmtDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommentService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostComment.java
Labels: fix, refactoring

#196 feat: 스웨거 인증 기능 활성화
  matzipback/src/main/java/com/matzip/matzipback/config/SwaggerConfig.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/util/CustomUserDetailService.java
  matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UsersDomainRepository.java
Labels: feat

#187 feat: #34 리스트 댓글 삭제 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCmtCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/DeleteListCmtRequset.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCmtCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListCmtDomainRepository.java
Labels: feat

#202 chore: #201 리스트 좋아요 등록/취소 기능 파일명 및 코드 수정
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/ListLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/ListLikeMessageReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/ListLikeReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/ListLikeService.java
Labels: chore
